# Generated by Django 3.0.7 on 2020-06-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='decription',
            new_name='description',
        ),
    ]
