# Generated by Django 3.0.7 on 2020-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=1, max_digits=10)),
                ('description', models.TextField(max_length=3000)),
                ('start_date', models.DateField(auto_now=True)),
                ('finish_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['budget'],
            },
        ),
    ]
