# Generated by Django 3.0.7 on 2020-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
