name: login on push
on: [push]

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: 'https://9f7b-190-108-214-63.ngrok.io/sendEmail'
        webhook_secret: 'supersecret'
        data: '{ "weapon": "hammer", "drink" : "beer" }'
