name: nexus email schedule
on: [push]

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      id: myRequest
      with:
        url: 'https://9f7b-190-108-214-63.ngrok.io/sendEmail'
        method: 'POST'

    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
